//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timetable_workshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_Subject()
        {
            this.Subject_Lecturer = new HashSet<Subject_Lecturer>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Course_ID { get; set; }
        public Nullable<int> Subject_ID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject_Lecturer> Subject_Lecturer { get; set; }
    }
}
