//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timetable_workshop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Timetable_proEntities : DbContext
    {
        public Timetable_proEntities()
            : base("name=Timetable_proEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Course_Subject> Course_Subject { get; set; }
        public virtual DbSet<Lecturer> Lecturers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Subject_Lecturer> Subject_Lecturer { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<View_lect> View_lect { get; set; }
        public virtual DbSet<View_Room> View_Room { get; set; }
        public virtual DbSet<View_sub2> View_sub2 { get; set; }
        public virtual DbSet<View_sub3> View_sub3 { get; set; }
        public virtual DbSet<viewSub> viewSubs { get; set; }
        public virtual DbSet<View_1DIT> View_1DIT { get; set; }
        public virtual DbSet<Slot> Slots { get; set; }
        public virtual DbSet<View_KiraSub> View_KiraSub { get; set; }
    }
}
