//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timetable_workshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public int ID { get; set; }
        public Nullable<int> Room_ID { get; set; }
        public Nullable<int> Lect_Sub_ID { get; set; }
        public Nullable<int> Course_ID { get; set; }
        public Nullable<int> Timetable_ID { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Room Room { get; set; }
        public virtual Subject_Lecturer Subject_Lecturer { get; set; }
        public virtual Timetable Timetable { get; set; }
    }
}
