//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timetable_workshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1DIT
    {
        public string SubjectName { get; set; }
        public string Name { get; set; }
        public string CodeName { get; set; }
        public int ID { get; set; }
        public int Expr1 { get; set; }
        public int TypeID { get; set; }
        public string TypeName { get; set; }
    }
}
