//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timetable_workshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_sub2
    {
        public int ID { get; set; }
        public string LecturerName { get; set; }
        public string Name { get; set; }
        public Nullable<int> Year { get; set; }
        public int TypeID { get; set; }
        public string Type { get; set; }
        public int sublectID { get; set; }
    }
}
