//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timetable_workshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_lect
    {
        public string Name { get; set; }
        public string Day { get; set; }
        public int ID { get; set; }
        public string NameSub { get; set; }
        public Nullable<int> Number { get; set; }
        public int LectID { get; set; }
        public int DayID { get; set; }
        public string CourseName { get; set; }
        public string RoomName { get; set; }
    }
}
